### ISSUE TITLE
controll aspect ratio

### ISSUE THREAD

**Issue by SchjarvenUtviklere** [matvp91/indigo-player#26]
I have some 4:5 videos, their dimensions are 1080 × 1350 and lower. 
When I add them into the indigo-player , then I get black bars on each side. as its fitting to player windows. I know I probably can control this by CSS on the player windows, but this will off course variate per display and so on. 

Therefor, introduce aspect ratio as a control, where either you can read the aspect ratio of the file natively, or it can be punched inn as a variable.

**Comment by matvp91** [comment]
@SchjarvenUtviklere I should have some time today to implement a config variable that allows you to set the aspect ratio.

Detecting it from the source is not a valid option because the containers are rendered before the video loads. At this point, the player is already in it's 16/9 aspect ratio size.

**Comment by Aanerud** [comment]
Awesome! 
BTW you need to add "by me a beer" button on you're project.

**Comment by matvp91** [comment]
See https://matvp91.github.io/indigo-player/#/Configuration?id=aspect-ratio

I'll surely check the "Buy me a beer" option. :)

**Comment by SchjarvenUtviklere** [comment]
Works perfect !
