### ISSUE TITLE
Adding custom videoTags

### ISSUE THREAD

**Issue by Aanerud** [matvp91/indigo-player#29]
Is it possible to either have a 

config = {
videoTags: **autoplay** loop muted, 
....

or a way to add the muted and loop variable ?
similar to the way you do autoplay: true,

**Comment by matvp91** [comment]
Hey @Aanerud , I'd rather not rely too heavily on the default behavior of the HTML5 video element, mainly because these kind of features need to be compatible with any possible player module. This is also the reason why `autoplay` is not handled by the video element but by the player (it does check if autoplay is allowed, and performs a `play()` action.

This would also break in combination with the `GoogleIMAExtension` and `FreeWheelExtension` which are responsible for ads. You don't want content looping when there is an adbreak that has to be played at the end of the video.

The API is fairly strict and handles these kind of cases for you (eg: ended is only called at the end of the video or video+last ad).

I've set up a small pin that does the following:
https://codepen.io/matvp91/pen/bJWzQg
- loop: At the end of the video (or video+last ad), player.play() is triggered again.
- muted: When the player is ready, `setVolume(0)` is called which mutes the player (& I've added player.play() afterwards in order to autoplay).

What are your two cents?

**Comment by Aanerud** [comment]
Well, the issue is that the Autoplay feature will work, on Safari, IOS, and Chrome ; 
if the video is muted, this is for "all" autoplay methods. 

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

"
Chrome's autoplay policies are simple:
Muted autoplay is always allowed.
"

https://webkit.org/blog/6784/new-video-policies-for-ios/

"
<video muted> elements will also be allowed to autoplay without a user gesture.
"

So, the loop tag you can ignore, as its nothing to do with Autoplay, 
but ** muted** should be something you can turn on and off.

**Comment by matvp91** [comment]
Calling `play()` after `setVolume(0)` as in the codepen should autoplay the video in muted state. See https://github.com/matvp91/indigo-player/blob/master/src/player/HTML5Player/HTML5Player.ts#L112

Meanwhile I'll look into adding a volume config variable that would allow you to set the video in muted state before autoplay kicks in.

**Comment by matvp91** [comment]
@Aanerud 1.3.5 is released with the possibility to provide an initial volume: https://matvp91.github.io/indigo-player/#/Configuration?id=initial-volume-amp-position

**Comment by Aanerud** [comment]
Hey @matvp91 
Did test now, 

https://video-ad-platform-aanerud.firebaseapp.com
and its not working, looks like the muted variable must be passed. 

Tested on Chrome and Safari. 
Firefox works like an charm :)

**Comment by matvp91** [comment]
The files are cached on jsdelivr CDN for ~24h, you're at v1.3.4 but the initial volume change is at v1.3.5.
![image](https://user-images.githubusercontent.com/12699796/56147968-9aa30f00-5fa9-11e9-88ae-99cc990b956a.png)

Can you quickly switch to `https://cdn.jsdelivr.net/npm/indigo-player@1.3.5/lib/indigo-player.js`? Although, once jsdelivr serves this version, it's best to switch back to indigo-player@1 (which subscribes to the major version only).

**Comment by Aanerud** [comment]
Works like a charm! 
removed image ;)
