### ISSUE TITLE
There is no method to switch video source

### ISSUE THREAD

**Issue by stoicbuddha** [matvp91/indigo-player#35]
**Is your feature request related to a problem? Please describe.**
I need to be able to switch the video source for a module I'm building that keeps the video behind a passwall (although I'll need to do this for paywall as well).

**Describe the solution you'd like**
I would like a method in the player object like `player.src` or `player.source` which would have the same format as [the regular source object](https://matvp91.github.io/indigo-player/#/Configuration?id=sources), which would allow source switching on the fly.

**Describe alternatives you've considered**
I have tried setting the source on the video element manually, but it throws a DOM Exception when I go to play the video 100% of the time.

**Comment by matvp91** [comment]
indigo-player does not support changing formats on the fly. However, it's best to destroy your first player (which will gracefully kill the instance and free memory) the in and initialize a new one. This is some sample code:

```javascript
let player = IndigoPlayer.init(container, firstConfig);
player.destroy();
player = IndigoPlayer.init(container, secondConfig);
```

**Comment by stoicbuddha** [comment]
Sorry, I should clarify: I don't want to switch formats, I want to switch sources (so HLS -> HLS). I fully understand why switching formats would be implausible, but switching media sources shouldn't be as big of a deal.

I did notice there is a `setSource` on `player` inside of the instance object, but that gives me the same result at this time (seems to switch, DOM Exception gets thrown when I try to play it).

**Comment by matvp91** [comment]
Using `player.setSource(...)` would break, because you're setting the HLS source directly to the video element this way. indigo-player takes care of loading your sources (which is one single format in the list of formats) by booting hlsjs for you and setting the correct MediaSource buffer to the video element.

Is there a reason why destroying and initializing the player a second time (which would not impact load time, as hlsjs media chunk is already fetched) would not work?

**Comment by stoicbuddha** [comment]
It looks like that may be what we end up having to do. I'm not opposed to it, it just wasn't feasible with our last player. I'll close this, as a solution technically exists. Perhaps something to add to the docs?

**Comment by stoicbuddha** [comment]
@matvp91 So I'm finally getting back to this, and am fine redrawing the player for switching source. However, I'm needing to do this within the module but I don't seem to have access to the top-level `player` variable from inside of the module unless I store the player in the global `window` and access it that way.

Is there a method to do this from within a module?

**Comment by matvp91** [comment]
Each facade returned by IndigoPlayer.init is specifically for the video asset provided in the config by design. I suggest adding code to switch the player in your page logic (which would simply call destroy and re-initiate the player, thus providing you a fresh facade).

**Comment by stoicbuddha** [comment]
The reason I am doing it from the module, is that the module is used for password wall functionality. If they know the password, they get to see the video.

For security reasons, we don't immediately make the proper m3u8 available, so we load in a generic trailer we have until we get the proper m3u8 after verifying the password.

Having this at the page level would break the encapsulation of the modules. I *could* make a `window`-scoped function that does the player redraw, but I'm also now realizing that `IndigoPlayer` is available via `window`. So I think I can redraw from within the module; I'll test and let you know.

**Comment by matvp91** [comment]
I remember we quickly discussed this in a different topic, and it makes me wonder, is there any reason why you would want to have the password confirmation part of the player & not part of the page?

IMO, this would fit your needs best:

- Request a password (by an input field).
- Check the password on your backend, when it matches, provide the playback URL.
- Start the player with the playback URL.

If I'm missing something, I'm sorry, it's been a while since we had this conversation. :)

**Comment by stoicbuddha** [comment]
We will be setting up a JS embed for the player, so we won't have access to the pages it is on.

What I currently do is hide the main ui (`.ig-ui`) and create an overlay with an input on top of the player. Once you submit the password, it checks it against our API and if the API sends back the proper response with a new source, I destroy the current player and reload it without the password plugin active.
